######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 22 19:10:01 2011
######################################################################

include ( ../config.pri )
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
